### ISSUE TITLE
Consider defaulting to UTF-8 encoding for configuration files?

### ISSUE THREAD

**Issue by greglucas** [FFY00/python-pyproject-metadata#36]
I'm working on switching over to meson-python for one of my projects and my installation was failing only on the Windows CI systems trying to decode the README. Windows doesn't use UTF-8 as the default system encoding (macosx and linux do), so if anyone has an emoji or some other unicode character in their readme file this will fail.

```
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-peb3otcz\overlay\Lib\site-packages\mesonpy\__init__.py", line 647, in __init__
      self._metadata = pyproject_metadata.StandardMetadata.from_pyproject(self._config, self._source_dir)
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-peb3otcz\overlay\Lib\site-packages\pyproject_metadata\__init__.py", line 236, in from_pyproject
      cls._get_readme(fetcher, project_dir),
    File "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-peb3otcz\overlay\Lib\site-packages\pyproject_metadata\__init__.py", line 434, in _get_readme
      text = file.read_text()
    File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\pathlib.py", line 1237, in read_text
      return f.read()
    File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1635: character maps to <undefined>
  error: subprocess-exited-with-error
```

Would it be reasonable to force the encoding in the `read_text(encoding="utf-8")` calls? I _think_ most people would expect this, and I was unaware that Windows didn't default to this on recent Python's until I hit this issue because I develop on macosx/linux machines. Happy to submit a PR if this is of interest.

**Comment by FFY00** [comment]
Yep, I was under the impression that was the default, but that's not the case! By default, it uses `locale.getencoding()` as the encoding, which is not UTF-8 on Windows. PEP 621 specifies the file is UTF-8, so adding the `encoding` argument is indeed the correct fix. Feel free to open a PR if you want :blush:

**Comment by greglucas** [comment]
> Yep, I was under the impression that was the default, but that's not the case!

I was also under that same impression :) and read through the long discourse threads on the topic. It looks like PEP 686 was approved https://peps.python.org/pep-0686/ and Python 3.15 will change the default, so they are being very conservative with the update and this will have to stay for a while.

**Comment by eli-schwartz** [comment]
> By default, it uses `locale.getencoding()` as the encoding, which is not UTF-8 on Windows.

Since it's explicitly affected by the PEP, I'm pretty sure that means it actually defaults to `locale.getpreferredencoding()`.

**Comment by eli-schwartz** [comment]
BTW as far as the whole forgetting to specify an encoding thing goes, Meson started setting up `$PYTHONWARNDEFAULTENCODING` back in March in order to detect stuff like this. Since python has a design bug where you cannot use `$PYTHONWARNINGS` to convert e.g. `mesonbuild.*` to errors, it might be necessary to [use warnings.filterwarnings in your source code](https://github.com/mesonbuild/meson/commit/a6e08e8fa7052c776989bf9410b87bf4d1f2ad49), but perhaps if your tests are in-process instead of Meson's project tests it can be done nicer...

Anyway, setting those warnings up by default turned out to be a very wise move for us.
