### ISSUE TITLE
Missing py.typed

### ISSUE THREAD

**Issue by pradyunsg** [FFY00/python-pyproject-metadata#7]
This project does not ship with a py.typed file in the distribution, resulting in mypy not being able to locate the type annotations for the `pep621` module.

**Comment by FFY00** [comment]
Uh, I think I need to convert the module to a package to be able to do that.

**Comment by FFY00** [comment]
Alternatively, we could install a `.pyi` file.

**Comment by FFY00** [comment]
#10 is going to make me rename the module, so I am gonna take that opportunity to make the module a package, so that we can add a `py.typed` file.
