### ISSUE TITLE
Wrong capitalization in "Author-email" metadata key

### ISSUE THREAD

**Issue by dalcinl** [FFY00/python-pyproject-metadata#71]
Source distribution metadata (`PKG-INFO` file) as generated by pyproject-metadata contains a key `Author-Email`, however the [specification](https://packaging.python.org/en/latest/specifications/core-metadata/#author-email) says the key should be capitalized as `Author-email`.  

To this project defense, it is very unfortunate that `Author-email` and `Maintainer-email` break the rules respect to all the other double-word keys in the spec.

Originally reported here: scikit-build/scikit-build-core#541

**Comment by dnicolodi** [comment]
`PKG-INFO` is in email message format as per RFC 5322 and has handled by the `email.parse` module when using the `compat32` policy. The header names in this format are case insensitive, thus the capitalization of the fields used here is just fine.

**Comment by henryiii** [comment]
Would it be better to go ahead and match it (since it's pretty simple to do), or would it be better to not rock the boat?

**Comment by dnicolodi** [comment]
I personally prefer the existing capitalization and I don't see any reason to change it.
